#!/usr/bin/env python3
"""Translate inner.html + script.js EN -> ES. Replaces visible text strings."""
import re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent / "src" / "site-clone"

# Ordered longest-first to avoid partial overlaps.
T = [
    # Top banner
    ("Bilingual service · American-format resumes ·", "Servicio bilingüe · Currículums en formato americano ·"),
    ("4,200+ clients helped", "+4,200 clientes ayudados"),
    # Nav
    ("How it works", "Cómo funciona"),
    ("Pricing", "Precios"),
    ("Reviews", "Reseñas"),
    ("FAQ", "Preguntas"),
    ("Get started", "Comenzar"),
    # Hero
    ("Built for the Hispanic community in the U.S.", "Hecho para la comunidad hispana en EE. UU."),
    ("Your American resume,", "Tu currículum americano,"),
    ("ready to land the job.", "listo para conseguir el trabajo."),
    ("We help you build a professional American-style resume, prepare for interviews in English, and develop a clear strategy to find a better job in the United States.",
     "Te ayudamos a construir un currículum profesional al estilo americano, prepararte para entrevistas en inglés y desarrollar una estrategia clara para encontrar un mejor trabajo en los Estados Unidos."),
    ("Get resume", "Obtener currículum"),
    ("+4,200 clients", "+4,200 clientes"),
    ("in the last 12 months", "en los últimos 12 meses"),
    ("based on 870+ reviews", "basado en +870 reseñas"),
    ("American resume", "Currículum americano"),
    ("ATS Score", "Puntuación ATS"),
    ("American format", "Formato americano"),
    ("Interviews", "Entrevistas"),
    ("&quot;Landed 3 interviews in my first week.&quot; — María G.",
     "&quot;Conseguí 3 entrevistas en mi primera semana.&quot; — María G."),
    # Clients section
    ("Our clients work at", "Nuestros clientes trabajan en"),
    # Problem section
    ("The problem", "El problema"),
    ("Finding a job in the U.S. as a Hispanic worker is harder than it should be.",
     "Encontrar un trabajo en EE. UU. siendo trabajador hispano es más difícil de lo que debería."),
    ("Your resume isn&#x27;t passing the filters", "Tu currículum no pasa los filtros"),
    ("U.S. companies use Applicant Tracking Systems (ATS) that reject poorly structured resumes before a human ever sees them.",
     "Las empresas en EE. UU. usan sistemas ATS que rechazan currículums mal estructurados antes de que un humano los vea."),
    ("English interviews are intimidating", "Las entrevistas en inglés intimidan"),
    ("Without practice answering typical American behavioral questions (STAR method), losing opportunities is very common.",
     "Sin práctica respondiendo preguntas conductuales típicas (método STAR), perder oportunidades es muy común."),
    ("You don&#x27;t know where to start", "No sabes por dónde empezar"),
    ("LinkedIn, Indeed, networking, cold emails... The wrong strategy can cost you months of searching.",
     "LinkedIn, Indeed, networking, correos en frío... La estrategia equivocada puede costarte meses de búsqueda."),
    # How it works
    ("Four steps. No friction.", "Cuatro pasos. Sin fricción."),
    ("Tell us about you", "Cuéntanos sobre ti"),
    ("Answer a short questionnaire about your experience, industry, and the kind of job you&#x27;re looking for.",
     "Responde un breve cuestionario sobre tu experiencia, industria y el tipo de trabajo que buscas."),
    ("Choose your package", "Elige tu paquete"),
    ("Pick the plan that best fits your situation and complete a secure payment.",
     "Elige el plan que mejor se adapte a tu situación y completa un pago seguro."),
    ("Upload your current resume", "Sube tu currículum actual"),
    ("If you already have one, upload it. If not, we&#x27;ll start from scratch with your professional information.",
     "Si ya tienes uno, súbelo. Si no, empezamos desde cero con tu información profesional."),
    ("Get your personalized plan", "Recibe tu plan personalizado"),
    ("Our team works on your case and delivers a resume and strategy ready to use.",
     "Nuestro equipo trabaja en tu caso y entrega un currículum y estrategia listos para usar."),
    # Expert support
    ("Expert support", "Soporte experto"),
    ("We speak Spanish. We think like American recruiters.",
     "Hablamos español. Pensamos como reclutadores americanos."),
    ("Our team combines bilingual specialists with U.S. human resources experience. We know exactly what recruiters look for and how to present you in the best possible way.",
     "Nuestro equipo combina especialistas bilingües con experiencia en recursos humanos en EE. UU. Sabemos exactamente lo que buscan los reclutadores y cómo presentarte de la mejor manera."),
    ("Right language", "Lenguaje correcto"),
    ("We turn &quot;Team lead&quot; into impact-driven phrases like &quot;Led cross-functional team of 12 to deliver 40% faster.&quot;",
     "Convertimos &quot;Líder de equipo&quot; en frases con impacto como &quot;Lideré equipo multifuncional de 12 personas para entregar 40% más rápido.&quot;"),
    ("Keywords", "Palabras clave"),
    ("We add the keywords ATS systems and recruiters in your industry are actively searching for.",
     "Añadimos las palabras clave que los sistemas ATS y los reclutadores de tu industria están buscando activamente."),
    ("Structure, spacing, and order that pass the filters at large U.S. companies.",
     "Estructura, espaciado y orden que pasan los filtros en grandes empresas de EE. UU."),
    ("Expert team", "Equipo experto"),
    # Templates
    ("Templates", "Plantillas"),
    ("Tested resume templates", "Plantillas de currículum probadas"),
    ("Use the templates U.S. recruiters love. Pick one and we'll build it for you in Word and PDF.",
     "Usa las plantillas que aman los reclutadores en EE. UU. Elige una y la construimos en Word y PDF."),
    ("Previous", "Anterior"),
    ("Next", "Siguiente"),
    # Pricing
    ("Pick the plan that fits you.", "Elige el plan que se ajuste a ti."),
    ("No subscriptions. Pay once for the service you need.",
     "Sin suscripciones. Paga una vez por el servicio que necesitas."),
    ("Review", "Revisión"),
    ("USD · one-time", "USD · pago único"),
    ("For those who already have a resume and want to know what to improve.",
     "Para quienes ya tienen un currículum y quieren saber qué mejorar."),
    ("Professional review of your current resume", "Revisión profesional de tu currículum actual"),
    ("Analysis of the main issues", "Análisis de los principales problemas"),
    ("Written list of recommendations", "Lista escrita de recomendaciones"),
    ("General job-search tips for the U.S.", "Consejos generales para buscar trabajo en EE. UU."),
    ("Start review", "Empezar revisión"),
    ("Most popular", "Más popular"),
    ("Professional", "Profesional"),
    ("The most popular. A brand-new resume from scratch in American style.",
     "El más popular. Un currículum nuevo desde cero al estilo americano."),
    ("Full rewrite in American style", "Reescritura completa al estilo americano"),
    ("Structure and content optimization (ATS)", "Optimización de estructura y contenido (ATS)"),
    ("LinkedIn profile help", "Ayuda con perfil de LinkedIn"),
    ("Interview preparation guide", "Guía de preparación para entrevistas"),
    ("Personalized job-search advice", "Asesoría personalizada de búsqueda de empleo"),
    ("Start Pro plan", "Empezar plan Pro"),
    ("Premium", "Premium"),
    ("Full white-glove support with 1-on-1 consulting.",
     "Soporte completo personalizado con consultoría 1 a 1."),
    ("Everything in the Professional plan", "Todo lo del plan Profesional"),
    ("Personal video consulting", "Consultoría personal por video"),
    ("Individual job-search strategy", "Estrategia individual de búsqueda de empleo"),
    ("Hands-on interview prep", "Preparación práctica de entrevistas"),
    ("Multiple resume revision rounds", "Múltiples rondas de revisión del currículum"),
    ("Priority support", "Soporte prioritario"),
    ("Start Premium", "Empezar Premium"),
    ("Trabajo Listo is not an employment agency and does not guarantee employment. We sell professional resume review, interview preparation, and career consulting services on a &quot;best effort&quot; basis.",
     "Trabajo Listo no es una agencia de empleo y no garantiza empleo. Vendemos servicios profesionales de revisión de currículum, preparación de entrevistas y consultoría de carrera bajo el principio de &quot;mejor esfuerzo&quot;."),
    # Reviews
    ("Ratings &amp; Reviews", "Calificaciones y reseñas"),
    ("out of 5", "de 5"),
    ("876 Reviews", "876 reseñas"),
    ("Most helpful reviews", "Reseñas más útiles"),
    ("Auto-scrolling · hover to pause", "Desplazamiento automático · pausa al pasar el cursor"),
    # Stats
    ("clients helped", "clientes ayudados"),
    ("satisfaction rate", "tasa de satisfacción"),
    ("bilingual support", "soporte bilingüe"),
    ("response time", "tiempo de respuesta"),
    # FAQ
    ("Frequently asked questions", "Preguntas frecuentes"),
    ("Will you really get me a job?", "¿De verdad me van a conseguir un trabajo?"),
    ("No. Trabajo Listo is not an employment agency. What we offer is a professional American-style resume, interview preparation, and job-search strategy. The final outcome depends on your experience, your effort, and the job market.",
     "No. Trabajo Listo no es una agencia de empleo. Lo que ofrecemos es un currículum profesional al estilo americano, preparación para entrevistas y estrategia de búsqueda de empleo. El resultado final depende de tu experiencia, tu esfuerzo y el mercado laboral."),
    ("We operate on a &quot;best effort&quot; basis.", "Operamos bajo el principio de &quot;mejor esfuerzo&quot;."),
    ("How fast will my resume be ready?", "¿Qué tan rápido estará listo mi currículum?"),
    ("The Review package ($49) is delivered within 48 hours. The Professional package ($249) takes 3 to 5 business days. The Premium ($549) can take 7 to 10 days because of the included consulting.",
     "El paquete de Revisión ($49) se entrega en 48 horas. El paquete Profesional ($249) tarda de 3 a 5 días hábiles. El Premium ($549) puede tomar de 7 a 10 días por la consultoría incluida."),
    ("Can I request changes if I don&#x27;t like it?", "¿Puedo pedir cambios si no me gusta?"),
    ("Yes. Every package includes at least one round of revisions. The Premium package includes multiple rounds until you&#x27;re fully satisfied.",
     "Sí. Cada paquete incluye al menos una ronda de revisiones. El paquete Premium incluye múltiples rondas hasta que estés totalmente satisfecho."),
    ("Do you handle specific industries?", "¿Manejan industrias específicas?"),
    ("Yes. We have worked with clients in construction, hospitality, healthcare, tech, education, transportation, retail, and professional services. We tailor the resume to your industry.",
     "Sí. Hemos trabajado con clientes en construcción, hostelería, salud, tecnología, educación, transporte, comercio y servicios profesionales. Adaptamos el currículum a tu industria."),
    ("Is my information safe?", "¿Está segura mi información?"),
    ("Yes. All your information is protected with SSL encryption and we never share your data with third parties. We comply with U.S. privacy regulations.",
     "Sí. Toda tu información está protegida con cifrado SSL y nunca compartimos tus datos con terceros. Cumplimos con las regulaciones de privacidad de EE. UU."),
    # CTA
    ("Your next job starts with a great resume.", "Tu próximo trabajo empieza con un gran currículum."),
    ("Join more than 4,200 Hispanic professionals who already upgraded their resume and their career in the U.S. with Trabajo Listo.",
     "Únete a más de 4,200 profesionales hispanos que ya mejoraron su currículum y su carrera en EE. UU. con Trabajo Listo."),
    ("Join", "Únete"),
    ("I have questions", "Tengo preguntas"),
    # Footer
    ("Professional resumes, interview preparation, and career strategy for the Hispanic community in the United States.",
     "Currículums profesionales, preparación de entrevistas y estrategia de carrera para la comunidad hispana en los Estados Unidos."),
    ("Service", "Servicio"),
    ("Legal", "Legal"),
    ("Terms of use", "Términos de uso"),
    ("Privacy policy", "Política de privacidad"),
    ("© 2024 Trabajo Listo. We are not an employment agency. We do not guarantee hiring, interviews, job offers, or income levels. Results depend on your experience, skills, and the job market.",
     "© 2024 Trabajo Listo. No somos una agencia de empleo. No garantizamos contratación, entrevistas, ofertas de trabajo ni niveles de ingresos. Los resultados dependen de tu experiencia, habilidades y el mercado laboral."),
    ("SSL secure", "SSL seguro"),
    ("Secure payment", "Pago seguro"),
    # Modal
    ("Step 1 of 5", "Paso 1 de 5"),
    ("Back", "Atrás"),
    ("Next →", "Siguiente →"),
    ("Close", "Cerrar"),
]

# Script.js translations
TS = [
    ("Use this template", "Usar esta plantilla"),
    ("Contact information", "Información de contacto"),
    ("Let's start with the basics. We'll only use these to deliver your resume.",
     "Empecemos con lo básico. Solo lo usaremos para entregar tu currículum."),
    ("First & last name", "Nombre y apellido"),
    ("Email", "Correo electrónico"),
    ("Phone", "Teléfono"),
    ("Preferred language", "Idioma preferido"),
    ("Your current situation", "Tu situación actual"),
    ("This helps us understand your level and the work involved.",
     "Esto nos ayuda a entender tu nivel y el trabajo necesario."),
    ("Are you currently working?", "¿Estás trabajando actualmente?"),
    ("Yes, full time", "Sí, tiempo completo"),
    ("Yes, part time", "Sí, medio tiempo"),
    ("No, actively searching", "No, buscando activamente"),
    ("Planning to search", "Planeo buscar"),
    ("Industry you want to work in", "Industria en la que quieres trabajar"),
    ("Construction / Trades", "Construcción / Oficios"),
    ("Warehouse / Logistics", "Almacén / Logística"),
    ("Hospitality / Restaurant", "Hostelería / Restaurantes"),
    ("Customer Service", "Servicio al cliente"),
    ("Healthcare", "Salud"),
    ("Office / Administration", "Oficina / Administración"),
    ("IT / Technology", "Tecnología / TI"),
    ("Other", "Otro"),
    ("Years of experience", "Años de experiencia"),
    ("No experience", "Sin experiencia"),
    ("Less than 1 year", "Menos de 1 año"),
    ("1–3 years", "1–3 años"),
    ("3–5 years", "3–5 años"),
    ("More than 5 years", "Más de 5 años"),
    ("Do you have a resume?", "¿Tienes un currículum?"),
    ("Yes, in English", "Sí, en inglés"),
    ("Yes, in Spanish", "Sí, en español"),
    ("Yes, in both", "Sí, en ambos"),
    ("English level", "Nivel de inglés"),
    ("Beginner", "Principiante"),
    ("Intermediate", "Intermedio"),
    ("Advanced", "Avanzado"),
    ("Fluent", "Fluido"),
    ("Resume details", "Detalles del currículum"),
    ("The more detail you share, the stronger your resume will be.",
     "Mientras más detalles compartas, más fuerte será tu currículum."),
    ("Desired job title", "Puesto deseado"),
    ("Key skills (comma separated)", "Habilidades clave (separadas por comas)"),
    ("Education", "Educación"),
    ("High school, technical school, college…", "Secundaria, escuela técnica, universidad…"),
    ("Certifications or licenses", "Certificaciones o licencias"),
    ("Last 2–3 jobs (company, role, dates, achievements)",
     "Últimos 2–3 trabajos (empresa, puesto, fechas, logros)"),
    ("Your biggest strength", "Tu mayor fortaleza"),
    ("Reliable, fast learner, leadership…", "Confiable, aprende rápido, liderazgo…"),
    ("What's your biggest challenge in your job search?", "¿Cuál es tu mayor desafío en la búsqueda de empleo?"),
    ("Few responses", "Pocas respuestas"),
    ("No interview invites", "Sin invitaciones a entrevistas"),
    ("Resume looks unprofessional", "Currículum se ve poco profesional"),
    ("Hard to explain my experience", "Difícil explicar mi experiencia"),
    ("Weak English", "Inglés débil"),
    ("Pick the level of support you want. We auto-recommended the best fit below.",
     "Elige el nivel de soporte que quieras. Recomendamos automáticamente la mejor opción."),
    ("Based on your answers we recommend the", "Según tus respuestas recomendamos el"),
    ("Resume Review", "Revisión de currículum"),
    ("Professional review with detailed feedback and rewrite suggestions.",
     "Revisión profesional con retroalimentación detallada y sugerencias de reescritura."),
    ("Resume Rewrite", "Reescritura de currículum"),
    ("Complete professional rewrite. ATS-optimized. Bilingual delivery.",
     "Reescritura profesional completa. Optimizada para ATS. Entrega bilingüe."),
    ("Premium Career Support", "Soporte Premium de carrera"),
    ("Full rewrite + LinkedIn + 1:1 interview coaching session.",
     "Reescritura completa + LinkedIn + sesión 1:1 de coaching de entrevista."),
    ("Recommended", "Recomendado"),
    ("Consent & checkout", "Consentimiento y pago"),
    ("Please confirm the following before we move to payment.",
     "Por favor confirma lo siguiente antes de pasar al pago."),
    ("I have read and agree to the Terms of Use and Privacy Policy.",
     "He leído y acepto los Términos de Uso y la Política de Privacidad."),
    ("I understand Trabajo Listo provides resume, interview prep, coaching and educational services.",
     "Entiendo que Trabajo Listo proporciona servicios de currículum, preparación de entrevistas, coaching y educación."),
    ("I understand Trabajo Listo is NOT an employer, staffing agency, or recruiting company.",
     "Entiendo que Trabajo Listo NO es un empleador, agencia de personal ni empresa de reclutamiento."),
    ("I understand purchasing does not guarantee employment, interviews, offers, income or any specific outcome.",
     "Entiendo que la compra no garantiza empleo, entrevistas, ofertas, ingresos ni ningún resultado específico."),
    ("I understand results depend on my experience, skills, language, qualifications and the labor market.",
     "Entiendo que los resultados dependen de mi experiencia, habilidades, idioma, calificaciones y mercado laboral."),
    ("All information I provided is true and current.",
     "Toda la información que proporcioné es verdadera y actual."),
    ("I understand refunds may be limited once personalized work has begun, per the refund policy.",
     "Entiendo que los reembolsos pueden ser limitados una vez iniciado el trabajo personalizado."),
    ("I agree to electronic order processing and accept that my consent is legally binding.",
     "Acepto el procesamiento electrónico del pedido y que mi consentimiento es legalmente vinculante."),
    ("I confirm I am of legal age and able to enter into contracts and make payments.",
     "Confirmo que soy mayor de edad y puedo celebrar contratos y realizar pagos."),
    ("I understand services are delivered on a best-effort basis without guaranteed outcomes.",
     "Entiendo que los servicios se entregan bajo el principio de mejor esfuerzo, sin resultados garantizados."),
    ("You're all set,", "¡Todo listo,"),
    ("amigo", "amigo"),
    ("We received your request for the", "Recibimos tu solicitud para el"),
    ("package", "paquete"),
    ("Our team will email", "Nuestro equipo enviará un correo a"),
    ("within 24 hours with payment details and next steps.",
     "en 24 horas con los detalles de pago y los próximos pasos."),
    ("Complete", "Completo"),
    ("Submit", "Enviar"),
    ("Classic", "Clásico"),
    ("Modern", "Moderno"),
    ("Regular", "Regular"),
    ("Minimal", "Minimalista"),
    ("Creative", "Creativo"),
    ("Executive", "Ejecutivo"),
    ("Step", "Paso"),
    ("of", "de"),
]

def translate(text, table):
    # Sort by length desc so longer phrases replace first
    for en, es in sorted(table, key=lambda p: -len(p[0])):
        text = text.replace(en, es)
    return text

html = (ROOT / "inner.html").read_text(encoding="utf-8")
out_html = translate(html, T)
# Swap nav language selector active state for ES
out_html = out_html.replace(
    '<a href="/" class="px-2 py-1 rounded-md bg-zinc-900 text-white">EN</a><a href="/es" class="px-2 py-1 rounded-md text-zinc-600 hover:bg-zinc-100">ES</a>',
    '<a href="/" class="px-2 py-1 rounded-md text-zinc-600 hover:bg-zinc-100">EN</a><a href="/es" class="px-2 py-1 rounded-md bg-zinc-900 text-white">ES</a>',
)
# Application link in ES
out_html = out_html.replace('href="/application"', 'href="/es/application"')
# Localize legal route links
out_html = out_html.replace('href="/terms"', 'href="/terms"').replace('href="/privacy"', 'href="/privacy"')
(ROOT / "inner.es.html").write_text(out_html, encoding="utf-8")

js = (ROOT / "script.js").read_text(encoding="utf-8")
out_js = translate(js, TS)
(ROOT / "script.es.js").write_text(out_js, encoding="utf-8")

print("Wrote inner.es.html and script.es.js")
