/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EsRouteImport } from './routes/es'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EsIndexRouteImport } from './routes/es.index'
import { Route as EsTermsRouteImport } from './routes/es.terms'
import { Route as EsPrivacyRouteImport } from './routes/es.privacy'
import { Route as EsApplicationRouteImport } from './routes/es.application'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EsRoute,
} as any)
const EsTermsRoute = EsTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => EsRoute,
} as any)
const EsPrivacyRoute = EsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => EsRoute,
} as any)
const EsApplicationRoute = EsApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => EsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/application': typeof ApplicationRoute
  '/es': typeof EsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/es/application': typeof EsApplicationRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/terms': typeof EsTermsRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application': typeof ApplicationRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/es/application': typeof EsApplicationRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/terms': typeof EsTermsRoute
  '/es': typeof EsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/application': typeof ApplicationRoute
  '/es': typeof EsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/es/application': typeof EsApplicationRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/terms': typeof EsTermsRoute
  '/es/': typeof EsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/application'
    | '/es'
    | '/privacy'
    | '/terms'
    | '/es/application'
    | '/es/privacy'
    | '/es/terms'
    | '/es/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application'
    | '/privacy'
    | '/terms'
    | '/es/application'
    | '/es/privacy'
    | '/es/terms'
    | '/es'
  id:
    | '__root__'
    | '/'
    | '/application'
    | '/es'
    | '/privacy'
    | '/terms'
    | '/es/application'
    | '/es/privacy'
    | '/es/terms'
    | '/es/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationRoute: typeof ApplicationRoute
  EsRoute: typeof EsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/terms': {
      id: '/es/terms'
      path: '/terms'
      fullPath: '/es/terms'
      preLoaderRoute: typeof EsTermsRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/privacy': {
      id: '/es/privacy'
      path: '/privacy'
      fullPath: '/es/privacy'
      preLoaderRoute: typeof EsPrivacyRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/application': {
      id: '/es/application'
      path: '/application'
      fullPath: '/es/application'
      preLoaderRoute: typeof EsApplicationRouteImport
      parentRoute: typeof EsRoute
    }
  }
}

interface EsRouteChildren {
  EsApplicationRoute: typeof EsApplicationRoute
  EsPrivacyRoute: typeof EsPrivacyRoute
  EsTermsRoute: typeof EsTermsRoute
  EsIndexRoute: typeof EsIndexRoute
}

const EsRouteChildren: EsRouteChildren = {
  EsApplicationRoute: EsApplicationRoute,
  EsPrivacyRoute: EsPrivacyRoute,
  EsTermsRoute: EsTermsRoute,
  EsIndexRoute: EsIndexRoute,
}

const EsRouteWithChildren = EsRoute._addFileChildren(EsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationRoute: ApplicationRoute,
  EsRoute: EsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
